#pragma once

#include "mycv/BoundingBox.cpp"
#include "mycv/Detector.cpp"
#include "mycv/FernClassifier.cpp"
#include "mycv/ForrestClassifier.cpp"
#include "mycv/HaarFeature.cpp"
#include "mycv/HaarFeaturesExtractor.cpp"
#include "mycv/Img.cpp"
#include "mycv/NccClassifier.cpp"
#include "mycv/RandomFern.cpp"
#include "mycv/RandomForest.cpp"
#include "mycv/RandomHaarFeature.cpp"
#include "mycv/RandomHaarFeatureExtractor.cpp"
#include "mycv/OneBitLBPExtractor.cpp"
